spring.application.name=MatchLens

# DeepSeek API Configuration
deepseek.api-key=tp-cjuq7ljrk7z72ei6r2rkbgsfk6ygk1dylcbpxbtomgou0a04
deepseek.base-url=https://api.deepseek.com
deepseek.model=deepseek-chat
